### ISSUE TITLE
Compile error on stable Rust: _error variable in lab/runtime.rs

### ISSUE THREAD

**Issue by csells** [Dicklesworthstone/asupersync#25]
## Description

Both the crates.io v0.2.7 release and the current git HEAD fail to compile on stable Rust (1.85+).

## Error

```
error[E0425]: cannot find value `error` in this scope
    --> src/lab/runtime.rs:1681:26
     |
1653 |         if let Err(_error) = handle.turn_with(Some(Duration::ZERO), |event, interest| {
     |                    ------ `_error` defined here
...
1681 |                 error = ?error,
     |                          ^^^^^
```

The variable is bound as `_error` (prefixed underscore, marking it unused) but then used in a `tracing::warn!` call as `error` (without underscore).

## Fix

Rename `_error` to `error` on line 1653 (or whichever line has the `if let Err(_error)`).

The crates.io v0.2.7 release also has a second error (`u128`/`u64` mismatch at line 1052) which appears to be fixed in git HEAD.

## Workaround

We vendor asupersync with local fixes applied.
